entryScript: score.py
runtime: python
condaDependenciesFile: scoringConfig.yml
sourceDirectory: 
enableGpu: False
baseImage: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04   # Explicit base image
