name: insurance_inference_env
dependencies:
  - python=3.9.*
  - pip
  - pip:
      - azureml-sdk
      - numpy
      - azureml-core
      - azureml-inference-server-http  # Ensures inference works
      - scikit-learn
      - inference-schema[numpy-support]
      - lightgbm
      - LightGBM
      - joblib # Ensure latest joblib version
      
