name: amlproj06_training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.9.*
  - pip

  - pip:
      - azureml-sdk
      - azureml-defaults
      - numpy
      - pandas
      - scikit-learn
      - inference-schema[numpy-support]
      - azure-storage-blob
      - joblib
      - wheel
      - setuptools
      - cmake
      - lightgbm==3.3.0
